name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Etiqueta quando aprovado
    runs-on: ubuntu-latest
    steps:
      - name: Etiqueta quando aprovado
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "Aprovado"
      
